### ISSUE TITLE
couple of minor typos

### ISSUE THREAD

**Issue by isimmons** [fespinoza/checklist_and_guides#1]
First thanks for this guide.

There are a couple of minor typos or some confusion on my part.
1. nowhere in the guide do we set a domain name of vagrantup.com (I"m not sure where to do that)
2. "sudo hostname vagrant" results in "unable to resolve host vagrant" message because the host name in /etc/hosts is set to "vagrant-precise32"
3. For the last step making the box. Again the name is "vagrant-precise32"

```
vagrant package --base vagrant-precise32
```

**Comment by fespinoza** [comment]
the guide has been updated, I fix the typo in the point 3.

the point 2 I'd have to prove all the commands again, maybe I forgot something when I did the guide, in any case you can test that and make a pull request with it if you are sure.

**Comment by sureshprasanna70** [comment]
@fespinoza I am also getting the same problem.Any directions to fix it?
